wbh:
	pandoc -s --template="../wbh.tex" --filter pandoc-xnos -o beispiel.tex beispiel.md	
	pandoc -s --template="../wbh.tex" --filter pandoc-xnos -o beispiel.pdf beispiel.md
	# Entferne die Kommentare um das erstellte PDF mit mupdf anzuzeigen
	#mupdf beispiel.pdf

